# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dcefc7b130159090b6f071f763813ecf32eae70f220c834d2caed51a9f76615d9820ca997687c02285ec140e1a465bc99b1640fa452d5160a8eea239fd7cdd9

test:
  secret_key_base: b933becc83f4dd6a5b19030ab520bf46f68e88c74a2c87dc33132a289d80140975f0ad33e7166a715ee1b6837f1e5c9e95109afdfb560d8700175247e74840e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
